config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  
  resources :articles  do
    get '/private', to: 'articles#private_articles', on: :collection
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :author, class_name: 'User'
    include Visible
    has_many :comments, dependent: :destroy
    has_one_attached :image

    paginates_per 5

    validates :title, presence: true, length: { in: 3..30 }
    validates :body, presence: true, length: { in: 5..255 }

    scope :public_ar, ->(value = "public") { where(status: value) }
    scope :private_ar, -> { public_ar("private") }
    scope :ordered, ->(direction = :desc) { order(created_at: direction) }
    scope :include_author, -> { includes(:author) }
    scope :search, -> (query) do
        return if query.blank?

        where('title LIKE ? OR title LIKE ?', "#{query.squish}%", "% #{query.squish}%")
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  def public?
    status == 'public'
  end
  def archived?
    status == 'archived'
  end
  def private?
    status == 'private'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :validatable
  has_many :articles, foreign_key: :author_id, inverse_of: :author
  ROLES = {
    user: 0,
    moder: 1,
    admin: 2
  }.with_indifferent_access.freeze

  enum role: ROLES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    def user_not_authorized
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to(request.referrer || root_path)
    end

protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  skip_before_action :verify_authenticity_token

  def index
    authorize Article
    @article = Article.new
    @articles = Article.public_ar.ordered.include_author.search(params[:query]).page params[:page]
  end

  def private_articles
    authorize Article
    
    @articles = current_user.admin? ? Article.all : current_user.articles
    @articles = @articles.private_ar.ordered.include_author
  end

  def show
    @article = Article.find(params[:id])
    authorize @article
  end

  def new
    @article = Article.new
    authorize Article 
  end

  def create
    authorize Article

    @article = Article.new(article_params)

    @article.author = current_user

    if @article.save
      redirect_to @article
      @notice = "Post was created successfuly"
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
    authorize @article
  end

  def update
    @article = Article.find(params[:id])
    authorize @article

    if @article.update(article_params)
      redirect_to @article
      @notice = "Post was edited successfuly"
    else
      render :edit
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    authorize @article

    @article.destroy
    @notice = "Post was deleted successfuly"
    redirect_to root_path
  end

private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController  
    before_action :authenticate_user!, only: %i[create destroy]  
    def create
        authorize Comment
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        @comment.commenter = current_user.username
        @comment.save
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        authorize @comment
        @comment.destroy
        redirect_to article_path(@article)
    end

private
    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<a class="text-dark text-decoration-none" href="<%= article_path(article) %>">
    <div class="my-3 p-3 bg-white rounded" style="box-shadow: 0px 5px 5px -1px #aaa">
        <div class="d-flex justify-content-between">
            <div class="d-inline">
                <h4 class="d-inline"><%= article.author.username %></h4>
                <p class="d-inline"> shared</p>
            </div>
            <p class="d-inline"> <%= article.created_at %></p>
        </div>
        <div class="d-flex justify-content-between">
            <h1 class="d-inline"><%= article.title %></h1>
        </div>
    </div>
</a>

app/views/articles/_form.html.erb
<div class="my-3 p-3 bg-white rounded" style="box-shadow: 0px 5px 5px -1px #aaa">
    <%= form_with model: article do |form| %>
    <div class="form-group">
        <div>Theme</div>
        <%= form.text_field :title , class: "form-control rounded"%>
        <% article.errors.full_messages_for(:title).each do |message|%>
        <div class="alert alert-warning p-1 mt-1 mb-0" role="alert">
            <div><%= message %></div>
        </div>
        <% end %>
    </div>

    <div class="form-group my-3">
        <div>What is on your mind?</div>
        <%= form.text_area :body , class: "form-control rounded", rows: "3"%>
        <% article.errors.full_messages_for(:body).each do |message| %>
        <div class="alert alert-warning p-1 mt-1 mb-0" role="alert">
            <div><%= message %></div>
        </div>
        <% end %>
    </div>

    <div class="form-group">
        <% if article.image.attached? %>
        <%= image_tag article.image, class: "w-100 d-block" %>
        <% end %>
        <%= form.file_field :image, class: "form-control rounded" %>
    </div>

    <div class="d-flex justify-content-between m-2">
        <div class="form-group">
            <%= form.select :status, ['public', 'private'], selected: 'public', class: "form-select"%>
        </div>
        <div>
            <%= form.submit "Post", class: "btn btn-outline-primary" %>
        </div>
    </div>
    <% end %>
</div>

app/views/articles/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark flex-nowrap,">
    <div class="container-fluid">
        <a class="navbar-brand fs-3 py-0" href="/articles">VizaĝoLib</a>
        <div>
            <%= form_with url: '/articles', method: :get do |form| %>
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <% if user_signed_in? %>
                <%= link_to 'Private', private_articles_path, class: "btn btn-outline-secondary me-4"%>
                <% end %>
                <li class="nav-item me-2">
                    <%= form.text_field :query, value: (params[:query]) ? params[:query].squish : '' , class: "form-control rounded", placeholder: "Search" %>
                </li>
                <li class="nav-item">
                    <%= form.submit "Search", class: "btn btn-outline-light" %>
                </li>
            </ul>
            <% end %>
        </div>
        <div class="text-white collapse navbar-collapse justify-content-end" id="navbarCollapse">
            <div>
                <% if user_signed_in? %>
                <%= current_user.username %>
                <% if current_user.admin? %>
                (admin)
                <% elsif current_user.moder? %>
                (moder)
                <% end %>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?' }, class: "btn btn-outline-primary" %>
                <% else %>
                <%= link_to 'Log in', new_user_session_path, class: "btn btn-outline-primary"%>
                <% end %>
            </div>
        </div>
    </div>
</nav>

app/views/articles/edit.html.erb
<%= render "header" %>

<div class="d-flex justify-content-center">
    <div class="w-50 mt-5 pt-5 d-block">
        <%= render "form", article: @article %>
    </div>
</div>

app/views/articles/index.html.erb
<%= render "header" %>

<div class="d-flex justify-content-center">
    <div class="w-50 d-block">
        <% if current_user %>
        <%= render 'form', article: @article %>
        <% else %>
        <div class="alert alert-light" role="alert">
            Login to post your articles.
        </div>
        <% end %>

        <% unless @articles.count == 0 %>
        <%= render @articles %>
        <div class="d-flex justify-content-center">
            <%= paginate @articles %>
        </div>
        <% else %>
        <div class="alert alert-info" role="alert">
            There are no articles that match specified parameter
        </div>
        <% end %>
    </div>
</div>

app/views/articles/new.html.erb
<%= render "header" %>

<div class="d-flex justify-content-center">
    <div class="w-50 d-block">
        <%= render "form", article: @article %>
    </div>
</div>

app/views/articles/private_articles.html.erb
<%= render "header" %>

<div class="d-flex justify-content-center">
    <div class="w-50 d-block">
        <h1> Private <% unless current_user.admin? %> <%= current_user.username %>'s <% end %> articles </h1>

        <% unless @articles.count == 0 %>
        <%= render @articles %>
        <% else %>
        <div class="alert alert-info" role="alert">
            All your articles are public
        </div>
        <% end %>
    </div>
</div>

app/views/articles/show.html.erb
<%= render "header" %>

<div class="d-flex justify-content-center">
    <div class="bg-light w-50 d-block">
        <div style="box-shadow: 0px 7px 5px -1px #eee" class="md-5 p-3">
            <div class="d-flex justify-content-between">
                <h1 class="d-inline"><%= @article.title %></h1>
                <div class="d-inline float-lg-left">
                    <% if policy(@article).update? %>
                    <a class="btn btn-outline-primary" href="<%= edit_article_path(@article) %>" role=" button">Edit</a>
                    <% end %>
                    <% if policy(@article).destroy? %>
                    <%= link_to "Destroy", article_path(@article), class: "btn btn-outline-danger",
                                method: :delete,
                                data: { confirm: "Are you sure?" } %>
                    <% end %>
                </div>
            </div>
            <h5><%= @article.body %></h5>
            <% if @article.image.attached? %>
            <%= image_tag @article.image, class: "card-img-top" %>
            <% end %>
            <div class="d-flex justify-content-end">
                By <%= @article.author.username %>
            </div>
        </div>
        <div>
            <% if current_user %>
            <div style="box-shadow: 0px 7px 5px -1px #eee" class="md-5 p-3">
                <%= render 'comments/form' %>
            </div>
            <% end %>
            <div style="box-shadow: 0px 7px 5px -1px #eee" class="md-5 p-3">
                <h3>Comments</h3>
                <%= render @article.comments %>
            </div>
        </div>
    </div>
</div>

app/views/comments/_comment.html.erb
<div class="p-2 d-flex justify-content-between">
    <% if comment.commenter %>
    <div>
        <strong><%= comment.commenter %>:</strong>
        <%= comment.body %>
    </div>
    <% if policy(comment).destroy? %>
    <div>
        <%= link_to 'Delete', [comment.article, comment], class: "btn btn-outline-danger",
                method: :delete,
                data: { confirm: "Are you sure?" } %>
    </div>
    <% end %>
    <% end %>
</div>

app/views/comments/_form.html.erb
<h5>Add comment</h5>
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
<div class="form-group">
    <%= form.text_area :body, class: "form-control" %>
</div>
<div class="d-flex justify-content-end mt-2">
    <%= form.submit class: "btn btn-outline-primary", value: "Comment" %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>PiKr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <br /><br /><br />
    <div class="d-flex justify-content-center">
        <% if !!alert %>
        <div class="alert alert-danger w-50" role="alert">
            <%= alert %>
        </div>
        <% end %>
        <% if !!notice %>
        <div class="alert alert-info w-50" role="alert">
            <%= notice %>
        </div>
        <% end %>
    </div>
    <%= yield %>
</body>

</html>